name: ci



on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: lint
        run: echo LINT

      - name: format
        run: echo FORMAT

      - name: build
        run: echo BUILD

      - name: test
        run: echo TEST

      - name: deploy
        run: echo DEPLOY
